TRUNCATE TABLE products RESTART IDENTITY CASCADE;

INSERT INTO products (sku, handle, title, category, family, model, variant, chip, storage_gb, ram_gb, screen_inch, color, region, sim, connectivity, price_aed, compare_at_aed, in_stock, tags, features, url) VALUES
('MFG14-256-ME',  'iphone-17-pro-max-256gb-silver-me',  'iPhone 17 Pro Max 256GB Silver - Middle East Version (Dual eSIM)',           'iPhone', 'iPhone 17', '17 Pro Max', 'Pro Max', 'A19 Pro', 256,  NULL, 6.9, 'Silver',          'Middle East',   'Dual eSIM',        '5G', 5599.00, 5999.00, TRUE, ARRAY['iphone','pro max','flagship'],             '{"camera_mp":48,"battery_hours":39,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-max-256gb-silver-me'),
('MFG15-256-INT', 'iphone-17-pro-max-256gb-silver-int', 'iPhone 17 Pro Max 256GB Silver With FaceTime - International (Dual eSIM)',   'iPhone', 'iPhone 17', '17 Pro Max', 'Pro Max', 'A19 Pro', 256,  NULL, 6.9, 'Silver',          'International', 'Dual eSIM',        '5G', 5699.00, 5999.00, TRUE, ARRAY['iphone','pro max','flagship'],             '{"camera_mp":48,"battery_hours":39,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-max-256gb-silver-int'),
('MFG16-512-INT', 'iphone-17-pro-max-512gb-cosmic-int', 'iPhone 17 Pro Max 512GB Cosmic Orange - International (Dual eSIM)',          'iPhone', 'iPhone 17', '17 Pro Max', 'Pro Max', 'A19 Pro', 512,  NULL, 6.9, 'Cosmic Orange',   'International', 'Dual eSIM',        '5G', 6249.00, 6599.00, TRUE, ARRAY['iphone','pro max','flagship'],             '{"camera_mp":48,"battery_hours":39,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-max-512gb-cosmic-int'),
('MFG17-1TB-INT', 'iphone-17-pro-max-1tb-deep-blue-int','iPhone 17 Pro Max 1TB Deep Blue Titanium - International (Dual eSIM)',       'iPhone', 'iPhone 17', '17 Pro Max', 'Pro Max', 'A19 Pro', 1024, NULL, 6.9, 'Deep Blue Titanium','International','Dual eSIM',        '5G', 7199.00, NULL,    TRUE, ARRAY['iphone','pro max','flagship'],             '{"camera_mp":48,"battery_hours":39,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-max-1tb-deep-blue-int'),

('MFG18-256-INT', 'iphone-17-pro-256gb-silver-int',     'iPhone 17 Pro 256GB Silver - International (Dual eSIM)',                    'iPhone', 'iPhone 17', '17 Pro',     'Pro',     'A19 Pro', 256,  NULL, 6.3, 'Silver',          'International', 'Dual eSIM',        '5G', 4699.00, 4999.00, TRUE, ARRAY['iphone','pro'],                             '{"camera_mp":48,"battery_hours":33,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-256gb-silver-int'),
('MFG19-512-ME',  'iphone-17-pro-512gb-cosmic-me',      'iPhone 17 Pro 512GB Cosmic Orange - Middle East Version (Dual eSIM)',       'iPhone', 'iPhone 17', '17 Pro',     'Pro',     'A19 Pro', 512,  NULL, 6.3, 'Cosmic Orange',   'Middle East',   'Dual eSIM',        '5G', 5199.00, 5499.00, TRUE, ARRAY['iphone','pro'],                             '{"camera_mp":48,"battery_hours":33,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-pro-512gb-cosmic-me'),

('MFG20-128-INT', 'iphone-17-128gb-black-int',          'iPhone 17 128GB Black - International (Dual eSIM)',                          'iPhone', 'iPhone 17', '17',         'Standard','A19',     128,  NULL, 6.3, 'Black',           'International', 'Dual eSIM',        '5G', 3399.00, 3599.00, TRUE, ARRAY['iphone'],                                    '{"camera_mp":48,"battery_hours":30,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-128gb-black-int'),
('MFG21-256-INT', 'iphone-17-256gb-lavender-int',       'iPhone 17 256GB Lavender - International (Dual eSIM)',                       'iPhone', 'iPhone 17', '17',         'Standard','A19',     256,  NULL, 6.3, 'Lavender',        'International', 'Dual eSIM',        '5G', 3799.00, NULL,    TRUE, ARRAY['iphone'],                                    '{"camera_mp":48,"battery_hours":30,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-256gb-lavender-int'),
('MFG22-512-ME',  'iphone-17-512gb-mist-blue-me',       'iPhone 17 512GB Mist Blue - Middle East Version (Dual eSIM)',                'iPhone', 'iPhone 17', '17',         'Standard','A19',     512,  NULL, 6.3, 'Mist Blue',       'Middle East',   'Dual eSIM',        '5G', 4199.00, NULL,    TRUE, ARRAY['iphone'],                                    '{"camera_mp":48,"battery_hours":30,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-17-512gb-mist-blue-me'),

('MFG23-256-INT', 'iphone-air-256gb-sky-blue-int',      'iPhone Air 256GB Sky Blue - International (Dual eSIM)',                      'iPhone', 'iPhone 17', 'Air',        'Air',     'A19 Pro', 256,  NULL, 6.5, 'Sky Blue',        'International', 'Dual eSIM',        '5G', 4199.00, 4499.00, TRUE, ARRAY['iphone','air','thin'],                      '{"camera_mp":48,"battery_hours":27,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-air-256gb-sky-blue-int'),
('MFG24-512-ME',  'iphone-air-512gb-space-black-me',    'iPhone Air 512GB Space Black - Middle East (Dual eSIM)',                     'iPhone', 'iPhone 17', 'Air',        'Air',     'A19 Pro', 512,  NULL, 6.5, 'Space Black',     'Middle East',   'Dual eSIM',        '5G', 4499.00, NULL,    TRUE, ARRAY['iphone','air','thin'],                      '{"camera_mp":48,"battery_hours":27,"refresh_hz":120,"ip":"IP68"}', 'https://example.com/products/iphone-air-512gb-space-black-me'),

('MFG25-128-INT', 'iphone-16e-128gb-black-int',         'iPhone 16e 128GB Black - International',                                     'iPhone', 'iPhone 16', '16e',        'e',       'A18',     128,  NULL, 6.1, 'Black',           'International', 'Dual eSIM',        '5G', 2399.00, 2699.00, TRUE, ARRAY['iphone','budget'],                          '{"camera_mp":48,"battery_hours":26,"refresh_hz":60,"ip":"IP68"}',  'https://example.com/products/iphone-16e-128gb-black-int'),
('MFG26-256-INT', 'iphone-16e-256gb-white-int',         'iPhone 16e 256GB White - International',                                     'iPhone', 'iPhone 16', '16e',        'e',       'A18',     256,  NULL, 6.1, 'White',           'International', 'Dual eSIM',        '5G', 2599.00, 2899.00, TRUE, ARRAY['iphone','budget'],                          '{"camera_mp":48,"battery_hours":26,"refresh_hz":60,"ip":"IP68"}',  'https://example.com/products/iphone-16e-256gb-white-int'),

('MFG30-256',     'ipad-pro-13-m5-256-wifi',            'iPad Pro 13-inch (M5) 256GB Wi-Fi - Space Black',                            'iPad',   'iPad Pro',  'M5',         NULL,      'M5',      256,  8,   13.0, 'Space Black',    NULL,            'Wi-Fi',            'Wi-Fi',4299.00, 4599.00, TRUE, ARRAY['ipad','pro'],                               '{"camera_mp":12,"battery_hours":10,"pencil":"Pro"}',                'https://example.com/products/ipad-pro-13-m5-256-wifi'),
('MFG31-1TB',     'ipad-pro-13-m5-1tb-cell',            'iPad Pro 13-inch (M5) 1TB Wi-Fi + Cellular - Space Black',                   'iPad',   'iPad Pro',  'M5',         NULL,      'M5',      1024, 16,  13.0, 'Space Black',    NULL,            'Wi-Fi + Cellular', '5G',  6199.00, NULL,    TRUE, ARRAY['ipad','pro'],                               '{"camera_mp":12,"battery_hours":10,"pencil":"Pro"}',                'https://example.com/products/ipad-pro-13-m5-1tb-cell'),
('MFG32-128',     'ipad-air-11-m3-128-wifi',            'iPad Air 11-inch (M3) 128GB Wi-Fi - Purple',                                 'iPad',   'iPad Air',  'M3',         NULL,      'M3',      128,  8,   11.0, 'Purple',         NULL,            'Wi-Fi',            'Wi-Fi',2499.00, 2699.00, TRUE, ARRAY['ipad','air'],                               '{"camera_mp":12,"battery_hours":10,"pencil":"Pro"}',                'https://example.com/products/ipad-air-11-m3-128-wifi'),
('MFG33-256',     'ipad-mini-a17-256',                  'iPad mini (A17 Pro) 256GB Wi-Fi - Starlight',                                'iPad',   'iPad mini', 'A17 Pro',    NULL,      'A17 Pro', 256,  8,   8.3,  'Starlight',      NULL,            'Wi-Fi',            'Wi-Fi',1899.00, 1999.00, TRUE, ARRAY['ipad','mini'],                              '{"camera_mp":12,"battery_hours":10,"pencil":"Pro"}',                'https://example.com/products/ipad-mini-a17-256'),

('MFG40-24-512',  'mbp-14-m5-pro-24-512-silver-en',     'MacBook Pro 14-inch (M5 Pro) 24GB / 512GB SSD - Silver / English Keyboard',  'Mac',    'MacBook Pro','14-inch',   'M5 Pro',  'M5 Pro',  512,  24,  14.2, 'Silver',         NULL,            NULL,               'Wi-Fi',7499.00, 7999.00, TRUE, ARRAY['mac','macbook','pro','laptop'],            '{"battery_hours":22,"ports":["TB5","HDMI","SD","MagSafe3"]}',      'https://example.com/products/mbp-14-m5-pro-24-512-silver-en'),
('MFG41-48-1TB',  'mbp-14-m5-max-48-1tb-space-black-en','MacBook Pro 14-inch (M5 Max) 48GB / 1TB SSD - Space Black / English',        'Mac',    'MacBook Pro','14-inch',   'M5 Max',  'M5 Max',  1024, 48,  14.2, 'Space Black',    NULL,            NULL,               'Wi-Fi',9799.00, NULL,    TRUE, ARRAY['mac','macbook','pro','laptop','creator'],  '{"battery_hours":20,"ports":["TB5","HDMI","SD","MagSafe3"]}',      'https://example.com/products/mbp-14-m5-max-48-1tb-space-black-en'),
('MFG42-64-2TB',  'mbp-16-m5-max-64-2tb-space-black-en','MacBook Pro 16-inch (M5 Max) 64GB / 2TB SSD - Space Black / English',        'Mac',    'MacBook Pro','16-inch',   'M5 Max',  'M5 Max',  2048, 64,  16.2, 'Space Black',    NULL,            NULL,               'Wi-Fi',13999.00, NULL,  TRUE, ARRAY['mac','macbook','pro','laptop','creator'],  '{"battery_hours":20,"ports":["TB5","HDMI","SD","MagSafe3"]}',      'https://example.com/products/mbp-16-m5-max-64-2tb-space-black-en'),

('MFG50-16-512',  'mba-13-m4-16-512-midnight-en',       'MacBook Air 13-inch (M4) 16GB / 512GB SSD - Midnight / English Keyboard',    'Mac',    'MacBook Air','13-inch',   'M4',      'M4',      512,  16,  13.6, 'Midnight',       NULL,            NULL,               'Wi-Fi',4799.00, 5099.00, TRUE, ARRAY['mac','macbook','air','laptop','student'],  '{"battery_hours":18,"ports":["TB4","MagSafe3"]}',                  'https://example.com/products/mba-13-m4-16-512-midnight-en'),
('MFG51-24-1TB',  'mba-15-m4-24-1tb-starlight-en',      'MacBook Air 15-inch (M4) 24GB / 1TB SSD - Starlight / English Keyboard',     'Mac',    'MacBook Air','15-inch',   'M4',      'M4',      1024, 24,  15.3, 'Starlight',      NULL,            NULL,               'Wi-Fi',6399.00, NULL,    TRUE, ARRAY['mac','macbook','air','laptop','student'],  '{"battery_hours":18,"ports":["TB4","MagSafe3"]}',                  'https://example.com/products/mba-15-m4-24-1tb-starlight-en'),
('MFG52-8-256',   'mba-13-m4-8-256-sky-en',             'MacBook Air 13-inch (M4) 8GB / 256GB SSD - Sky Blue / English Keyboard',     'Mac',    'MacBook Air','13-inch',   'M4',      'M4',      256,  8,   13.6, 'Sky Blue',       NULL,            NULL,               'Wi-Fi',3899.00, NULL,    TRUE, ARRAY['mac','macbook','air','laptop','student','budget'],'{"battery_hours":18,"ports":["TB4","MagSafe3"]}',        'https://example.com/products/mba-13-m4-8-256-sky-en'),

('MFG60-16-512',  'mac-mini-m4-16-512',                 'Mac mini (M4) 16GB / 512GB SSD',                                             'Mac',    'Mac mini',  'M4',         'M4',      'M4',      512,  16,  NULL, NULL,             NULL,            NULL,               'Wi-Fi',3299.00, 3499.00, TRUE, ARRAY['mac','mini','desktop'],                    '{"ports":["TB4","TB4","USB-C","Ethernet"]}',                       'https://example.com/products/mac-mini-m4-16-512'),
('MFG61-24-1TB',  'mac-mini-m4-pro-24-1tb',             'Mac mini (M4 Pro) 24GB / 1TB SSD',                                           'Mac',    'Mac mini',  'M4 Pro',     'M4 Pro',  'M4 Pro',  1024, 24,  NULL, NULL,             NULL,            NULL,               'Wi-Fi',5599.00, NULL,    TRUE, ARRAY['mac','mini','desktop','creator'],          '{"ports":["TB5","TB5","TB5","Ethernet"]}',                         'https://example.com/products/mac-mini-m4-pro-24-1tb');
