#!/usr/bin/env node
// Fetches Apple UAE product pages, extracts text, writes to config/apple_current_lineup.md.
// Runs on a schedule (via supervisor) so the bot always has fresh product lineup data.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, '..', 'config', 'apple_current_lineup.md');

const PAGES = [
  { name: 'MacBook Air',   url: 'https://www.apple.com/ae/shop/buy-mac/macbook-air' },
  { name: 'MacBook Pro',   url: 'https://www.apple.com/ae/shop/buy-mac/macbook-pro' },
  { name: 'Mac mini',      url: 'https://www.apple.com/ae/mac-mini/specs/' },
  { name: 'Mac Studio',    url: 'https://www.apple.com/ae/mac-studio/specs/' },
  { name: 'iMac',          url: 'https://www.apple.com/ae/imac/specs/' },
  { name: 'iPad Pro',      url: 'https://www.apple.com/ae/ipad-pro/specs/' },
  { name: 'iPad Air',      url: 'https://www.apple.com/ae/ipad-air/specs/' },
  { name: 'iPad mini',     url: 'https://www.apple.com/ae/ipad-mini/specs/' },
  { name: 'iPad',          url: 'https://www.apple.com/ae/shop/buy-ipad/ipad' },
  { name: 'iPhone 17 Pro', url: 'https://www.apple.com/ae/iphone-17-pro/specs/' },
  { name: 'iPhone 17',     url: 'https://www.apple.com/ae/iphone-17/specs/' },
  { name: 'iPhone Air',    url: 'https://www.apple.com/ae/iphone-air/specs/' },
  { name: 'iPhone 17e',    url: 'https://www.apple.com/ae/iphone-17e/specs/' },
  { name: 'iPhone 16',     url: 'https://www.apple.com/ae/iphone-16/specs/' },
  { name: 'Apple Watch Series 11', url: 'https://www.apple.com/ae/apple-watch-series-11/specs/' },
  { name: 'Apple Watch Ultra 3',   url: 'https://www.apple.com/ae/apple-watch-ultra-3/specs/' },
  { name: 'Apple Watch SE 3',      url: 'https://www.apple.com/ae/apple-watch-se/specs/' },
  { name: 'AirPods 4',     url: 'https://www.apple.com/ae/airpods-4/specs/' },
  { name: 'AirPods Pro 3', url: 'https://www.apple.com/ae/airpods-pro/specs/' },
  { name: 'AirPods Max 2', url: 'https://www.apple.com/ae/airpods-max/specs/' },
];

const FETCH_TIMEOUT_MS = 12_000;
const CONCURRENCY = 4;

function stripHtml(html) {
  return String(html || '')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

function extractSpecs(text, pageName) {
  const out = new Set();
  const specPatterns = [
    /\b(Apple\s+)?M[1-9](\s+(Pro|Max|Ultra))?\s+chip\b/gi,
    /\bA\d{2}(\s+Pro)?\s+chip\b/gi,
    /\b(S10|S11|S9|S12)\s+SiP\b/gi,
    /\bH\d\s+chip\b/gi,
    /\b\d{1,2}(\.\d+)?[-\s]?inch\b/gi,
    /\b\d{2,3}\s*GB\s+unified\s+memory\b/gi,
    /\b\d{3,4}\s*GB\s+SSD\b/gi,
    /\b\d\s*TB\s+SSD\b/gi,
    /\bcolors?\s*:\s*[A-Z][^.;]{3,80}/gi,
    /\b(Space\s+(Black|Gray|Grey)|Silver|Midnight|Starlight|Sky\s+Blue|Deep\s+Blue(\s+Titanium)?|Cosmic\s+Orange|Light\s+Gold|Cloud\s+White|Natural\s+Titanium)\b/gi,
  ];
  for (const re of specPatterns) {
    const matches = text.match(re) || [];
    for (const m of matches) out.add(m.trim());
  }
  return Array.from(out).slice(0, 40);
}

async function fetchOne(page) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const r = await fetch(page.url, {
      signal: controller.signal,
      headers: { 'User-Agent': 'alAsil-bot-sync/1.0 (+mailto:support@alasil.ae)', 'Accept': 'text/html' },
      redirect: 'follow',
    });
    if (!r.ok) return { page, ok: false, err: `HTTP ${r.status}` };
    const html = await r.text();
    const text = stripHtml(html).slice(0, 8000);
    const facts = extractSpecs(text, page.name);
    return { page, ok: true, text, facts };
  } catch (err) {
    return { page, ok: false, err: String(err?.message || err) };
  } finally {
    clearTimeout(timer);
  }
}

async function runBatch(items, size, fn) {
  const out = [];
  for (let i = 0; i < items.length; i += size) {
    const batch = items.slice(i, i + size);
    const res = await Promise.all(batch.map(fn));
    out.push(...res);
  }
  return out;
}

function buildMarkdown(results) {
  const now = new Date().toISOString();
  const lines = [];
  lines.push(`# Apple Current Lineup Snapshot (auto-synced from apple.com/ae)`);
  lines.push('');
  lines.push(`_Last synced: ${now}_`);
  lines.push('');
  lines.push('This file is auto-generated by `scripts/sync-apple.js`. It holds the CURRENT lineup as advertised on apple.com/ae. The bot uses this alongside `apple_specs.md` to answer spec / availability questions based on today\'s Apple catalog, not stale training data.');
  lines.push('');
  for (const r of results) {
    lines.push(`## ${r.page.name}`);
    lines.push(`Source: ${r.page.url}`);
    if (!r.ok) {
      lines.push(`_Fetch failed: ${r.err}_`);
      lines.push('');
      continue;
    }
    if (r.facts.length) {
      lines.push('Key facts detected:');
      for (const f of r.facts) lines.push(`- ${f}`);
    }
    lines.push('');
    lines.push('Raw excerpt (first 1.5k chars):');
    lines.push('```');
    lines.push(r.text.slice(0, 1500));
    lines.push('```');
    lines.push('');
  }
  return lines.join('\n');
}

(async () => {
  const started = Date.now();
  console.log(`[sync-apple] starting fetch of ${PAGES.length} pages...`);
  const results = await runBatch(PAGES, CONCURRENCY, fetchOne);
  const ok = results.filter((r) => r.ok).length;
  const fail = results.length - ok;
  const md = buildMarkdown(results);
  fs.writeFileSync(OUT_PATH, md);
  const ms = Date.now() - started;
  console.log(`[sync-apple] wrote ${OUT_PATH} (${md.length} bytes) — ok=${ok} fail=${fail} in ${ms}ms`);
})().catch((err) => {
  console.error('[sync-apple] fatal:', err);
  process.exit(1);
});
